/*
 * This file was automatically generated by EvoSuite
 * Fri May 28 16:29:02 GMT 2021
 */

package org.jabref.logic.formatter.bibtexfields;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.formatter.bibtexfields.ReplaceTabsBySpaceFormater;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ReplaceTabsBySpaceFormater_ESTest extends ReplaceTabsBySpaceFormater_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.format("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      // Undeclared exception!
      try { 
        replaceTabsBySpaceFormater0.format((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.format("remove_tabs");
      assertEquals("remove_tabs", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.getKey();
      assertEquals("remove_tabs", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.getExampleInput();
      assertEquals("In \t\t CDMA", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.getName();
      assertEquals("Replace tabs with space", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ReplaceTabsBySpaceFormater replaceTabsBySpaceFormater0 = new ReplaceTabsBySpaceFormater();
      String string0 = replaceTabsBySpaceFormater0.getDescription();
      assertEquals("Replace tabs with space in the field content.", string0);
  }
}
