/*
 * This file was automatically generated by EvoSuite
 * Sun May 30 12:26:26 GMT 2021
 */

package org.jabref.logic.formatter.casechanger;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.formatter.casechanger.LowerCaseFormatter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LowerCaseFormatter_ESTest extends LowerCaseFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.format("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      // Undeclared exception!
      try { 
        lowerCaseFormatter0.format((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"String.length()\" because \"title\" is null
         //
         verifyException("org.jabref.logic.formatter.casechanger.TitleParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.getKey();
      assertEquals("lower_case", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.format("lower_case");
      assertEquals("lower_case", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.getDescription();
      assertEquals("Changes all letters to lower case.", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.getExampleInput();
      assertEquals("KDE {Amarok}", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LowerCaseFormatter lowerCaseFormatter0 = new LowerCaseFormatter();
      String string0 = lowerCaseFormatter0.getName();
      assertEquals("Lower case", string0);
  }
}
