/*
 * This file was automatically generated by EvoSuite
 * Sat May 29 14:28:17 GMT 2021
 */

package org.jabref.logic.importer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.importer.AuthorListParser;
import org.jabref.model.entry.AuthorList;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AuthorListParser_ESTest extends AuthorListParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("3}[U/N&w~)8}eR2}");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      AuthorList authorList0 = authorListParser0.parse("");
      assertEquals(0, authorList0.getNumberOfAuthors());
      assertTrue(authorList0.isEmpty());
      assertNotNull(authorList0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("RuU\"PRidE`# j^M");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("B(>M|g!)Q,L+2");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("i6[I~,*iFp");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse(",2-");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("p6I.F{1}03c");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("[{ I8l");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("f{7^y7 !mg`m");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("),eW~LD%L86ME");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("031WX[,p)YV`sAxE");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("bMA}U%Lrc R,MJi5=s|");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("k,,hI");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse(",z:,-");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("d:/XeD8+a2J?Yr,");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      assertNotNull(authorListParser0);
      
      // Undeclared exception!
      try { 
        authorListParser0.parse("0Zx~`S1yx-");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse("z<6v[]LgL~nU\"oZt6^");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse("d6}Uu-(_hNwAzM5");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse("1wzU_~O9^U8j1ps {");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse(":/e8+,?,r,");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse("EpRsSw[9~qLt;yG1R");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      AuthorList authorList0 = authorListParser0.parse(", and ");
      assertTrue(authorList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      AuthorListParser authorListParser0 = new AuthorListParser();
      // Undeclared exception!
      try { 
        authorListParser0.parse("d:/FeD8+,2J?Yr,");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }
}
