/*
 * This file was automatically generated by EvoSuite
 * Fri May 28 11:41:05 GMT 2021
 */

package org.jabref.logic.layout.format;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.layout.format.CreateBibORDFAuthors;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CreateBibORDFAuthors_ESTest extends CreateBibORDFAuthors_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CreateBibORDFAuthors createBibORDFAuthors0 = new CreateBibORDFAuthors();
      String string0 = createBibORDFAuthors0.format(" and ");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CreateBibORDFAuthors createBibORDFAuthors0 = new CreateBibORDFAuthors();
      // Undeclared exception!
      try { 
        createBibORDFAuthors0.format((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"String.contains(java.lang.CharSequence)\" because \"fieldText\" is null
         //
         verifyException("org.jabref.logic.layout.format.CreateBibORDFAuthors", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CreateBibORDFAuthors createBibORDFAuthors0 = new CreateBibORDFAuthors();
      String string0 = createBibORDFAuthors0.format("");
      assertEquals("<bibo:contribution>\n  <bibo:Contribution>\n    <bibo:role rdf:resource=\"http://purl.org/ontology/bibo/roles/author\" />\n    <bibo:contributor><foaf:Person foaf:name=\"\"/></bibo:contributor>\n    <bibo:position>1</bibo:position>\n  </bibo:Contribution>\n</bibo:contribution>\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CreateBibORDFAuthors createBibORDFAuthors0 = new CreateBibORDFAuthors();
      String string0 = createBibORDFAuthors0.format("  and ");
      assertEquals("<bibo:contribution>\n  <bibo:Contribution>\n    <bibo:role rdf:resource=\"http://purl.org/ontology/bibo/roles/author\" />\n    <bibo:contributor><foaf:Person foaf:name=\" \"/></bibo:contributor>\n    <bibo:position>1</bibo:position>\n  </bibo:Contribution>\n</bibo:contribution>\n", string0);
  }
}
