/*
 * This file was automatically generated by EvoSuite
 * Fri May 28 14:03:26 GMT 2021
 */

package org.jabref.logic.integrity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.integrity.BracesCorrector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BracesCorrector_ESTest extends BracesCorrector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = BracesCorrector.apply("G>1}8wh.%oH\"@UPb}jW");
      assertEquals("{{G>1}8wh.%oH\"@UPb}jW", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = BracesCorrector.apply("(\\{)|(\\})");
      assertEquals("(\\{)|(\\})", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = BracesCorrector.apply("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = BracesCorrector.apply("$KI[,Uj$;A/Q{{");
      assertEquals("$KI[,Uj$;A/Q{{}}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = BracesCorrector.apply((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      BracesCorrector bracesCorrector0 = new BracesCorrector();
  }
}
