/*
 * This file was automatically generated by EvoSuite
 * Fri May 28 08:44:12 GMT 2021
 */

package org.jabref.logic.integrity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jabref.logic.integrity.DateChecker;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DateChecker_ESTest extends DateChecker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DateChecker dateChecker0 = new DateChecker();
      // Undeclared exception!
      try { 
        dateChecker0.checkValue("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/StringUtils
         //
         verifyException("org.jabref.model.strings.StringUtil", e);
      }
  }
}
